@baseUrl = http://localhost:8000
@urlPath = api/v1

POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "manish test email",
  "email": "mitchel.lemke47@ethereal.email",
  "password":"328043",
  "phoneNumber":"5390734233"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "mitchel.lemke47@ethereal.email",
  "password":"328043"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "mitchel.lemke47@ethereal.email"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/fg
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "328043",
  "confirmPassword":"328043"
}