@baseUrl = http://localhost:8000
@urlPath = api/v1

POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "manish",
  "email": "manish4123@gmail.com",
  "password":"328043",
  "phoneNumber":"5320732323"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "manish4123@gmail.com",
  "password":"328043"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true
